### PR TITLE
Remove dependency on assert

### PR DESCRIPTION
**Pull request by tomek-he-him**
Hi @podefr, cosmosio/shallow-diff#2 applies here as well.

### CODE REVIEW

**Comment by podefr** [comment]
Hey Tomek,

Thanks for the suggestion. I understand that assert may not be a good choice given the v8 and size limitations, but I still need to ensure that the parameters are of the expected types. Also, this would fail the tests (npm test) because the tests are expecting an error to be thrown.

Could you suggest a replacement, another assert lib that would do the same thing and update your PR?

Thanks a lot for your contribution!
Olivier

**Comment by tomek-he-him** [comment]
Hi Olivier,

I replaced `assert` with the good old `if (thingsGoWrong) throw new Error`. All tests pass on my machine :)

https://github.com/tomekwi/simple-loop/blob/f29ecd0/index.js#L19-L24

**Comment by podefr** [comment]
Thanks Tomek! I'll merge it and publish a new version to npm.

**Comment by podefr** [comment]
I published 0.0.4, thanks!

**Comment by tomek-he-him** [comment]
:+1:

**Pull request merged**
